sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install texlive-full cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
- bash make.sh
deploy:
- provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  on:
    branch: master
env:
  global:
  - secure: b94sIa1GMld4ma61H7s9ajeoteo/oabhHDxrXO9VHYame4QpId7peb59jolwhR2O0q2vhfgnz0Zl54LF4VQAA58Xh4/K7ZAT+5kcs5Mf2eM/1kB1rEQ6kgXVHR+os68Z6VSqPVisc0zRv/60XFYUz0sfd/aHv4mfkGXxug+xkqWsoKYB9J2sRk1PeuvLNYVhQlt8xuLF3nOb/hsQeRw7P3VjdFn7xqfNQpv48bXV3QsmmlgKaABvJq2ajvVwEdwX4+yd/AALacdCTAMvRwtASbnzPxzx7W4Q3pERSP/qqZrkXFduRvpjiibPesJnRH+RAy9RUKRVdj9mRAjXazG4XQpwtzPJPrmqf450p4vtS61Zh+b3MDDTJnix8aewPadQqG6A/yuTA0lYfeXmCjRDJ8On/Uom+9J1rsMwFlFaFXtz598+s22rltvapmNPZa+Df/LsUEoVFBB8O3a1itjybCu51EyQX8BlUNP0ttgmsn3zc1ZgckTEeJkjtJKmSZpk7nBLwVA9BeWNkR/2soDRnLrifQjjBWTdrKu1dZUanadHNJReazjhx4dDE5iOt2vdXf/MgwPSYBF5pkTwm4fyHhPBmgEzE5i+qU6FyDQhZ7ZRBNTMn5KQ5hhiMvzOGP9Wt6NdfQm5r8PUALIdBO3vOZ2rCS7V56kV6D+7sMscdY0=
