#!/usr/bin/python3

import pandas as pd

fns = ['data/data.csv', 'data/tips.csv']

for fn in fns:
    df = pd.read_csv(fn)
    
    df.loc[df['specificaties'].isna(), 'specificaties'] = ''
    
    df = df.iloc[df['specificaties'].str.casefold().argsort(kind='mergesort')]
    df = df.iloc[df['Wat?'].str.casefold().argsort(kind='mergesort')]
    
    df.to_csv(fn, index=False)
